language: python

install:
  - |
    pip install --egg --no-binary pyenv pyenv
    export PATH=~/.pyenv/bin:$PATH
    eval "$(pyenv init -)"
    env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install --skip-existing $PYTHON_VERSION
    pyenv global $PYTHON_VERSION
    pyenv shell $PYTHON_VERSION
    pip install -U pip setuptools wheel py
    pip install .

matrix:
  include:
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6.2
    - os: osx
      language: generic
      env: PYTHON_VERSION=2.7.10
    - os: osx
      language: generic
      env: PYTHON_VERSION=2.7.5
    - os: osx
      language: generic
      env: PYTHON_VERSION=2.7.2
    - os: osx
      language: generic
      env: PYTHON_VERSION=2.7.1

script: python setup.py test
