language: python

install:
  - |
    eval "$(pyenv init -)"
    env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install --skip-existing $PYTHON_VERSION
    pyenv global $PYTHON_VERSION
    pyenv shell $PYTHON_VERSION
    pip install -U pip setuptools wheel
    pip install .

matrix:
  include:
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6.2
    - os: osx
      language: generic
      env: PYTHON_VERSION=2.7.13

script: python setup.py test
